# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            '轻文学独立裁判'
tagline:          'Lighterature Independent Verdiction'
description:      "I'm selecting literature can be desecribed as 'light' and light-novel can be described as 'literature'"
url:              http://applnow.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/poole/hyde
