# Dependencies
markdown:         kramdown
highlighter:      rouge
safe: true

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            '轻文学独立裁判'
tagline:          'Lighterature Independent Verdiction'
description:      "I am choosing literary works can be categorized as 'light', alongside light novels with literary value."
url:              http://applnow.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         7

# Custom vars
version:          0.7

github:
  repo:           https://github.com/Applnow/applnow.github.io.git
include:
  - images
  - public/images
destination: _site
